app/Http/Controllers/StateController.php
app/State.php
database/factories/StateFactory.php
database/migrations/2019_09_26_031428_create_states_table.php
resources/views/admin/states.blade.php
routes/web.php

State maintenance and merge with CM.

State maintenance

---

.gitignore
resources/views/admin/listState.blade.php

Please upload this file listState.blade.php

List of states

---

app/Http/Controllers/MiscController.php
config/adminlte.php
resources/lang/vendor/adminlte/en/adminlte.php
resources/lang/vendor/adminlte/en/menu.php
resources/views/staff/liststaff.blade.php
resources/views/staff/searchstaff.blade.php
routes/web.php

Add search function and list user

Search function

---

app/Http/Controllers/Admin/StateController.php
app/Shared/LdapHelper.php
resources/views/admin/states.blade.php
routes/web.php

1. - masuk dlm folder admin,
2. - have to login to access STATE admin
3. - All POST request ( update, destroy) will properly redirect to GET (admin/state/show)
4. - remove mobile from ldap session

STATES and mobile session update

---

app/Http/Controllers/Admin/StateController.php
app/Http/Controllers/Auth/LoginController.php
app/User.php
composer.json
composer.lock
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2019_10_02_082913_user_disable_autoincrement.php

Update user to use persno instead of running number as ID.
Remove autoincrement from table users

Update user to use persno instead of running number as ID

---

app/DayType.php
app/Http/Controllers/DayTypeController.php
app/Shared/MathHelper.php
config/adminlte.php
database/migrations/2019_10_03_042253_create_day_types_table.php
resources/lang/vendor/adminlte/en/menu.php
resources/views/admin/shiftp/daytype.blade.php
routes/web.php

defind day type, start work time, and work duration

work day CRUD

---

app/Http/Controllers/MiscController.php
database/migrations/2014_10_12_000000_create_users_table.php

function listloguser
migration table users column id add primary key & unsigned

2 changes function & migration

---

app/Company.php
app/Http/Controllers/Admin/CompanyController.php
app/Http/Controllers/RoleController.php
app/User.php
config/adminlte.php
database/migrations/2019_09_29_143225_create_companies_table.php
resources/views/admin/companies.blade.php
resources/views/admin/listCompany.blade.php
routes/web.php

Request to pull company mngmnt

---

app/Http/Controllers/Admin/RoleController.php
app/Http/Controllers/Admin/StaffController.php
app/Http/Controllers/MiscController.php
app/Http/Controllers/TempController.php
resources/views/admin/staff.blade.php
resources/views/loginoffline.blade.php
resources/views/staff/liststaff.blade.php
routes/web.php

-Add offline login function
-Add logs when role CRUD

offline login & role CRUD logs

---

app/Shared/LdapHelper.php
composer.json

to cater populating user data using ldap and chenge the user id to use persno

populate employeee data using persno

---

app/Http/Controllers/ShiftGroupController.php
app/Http/Controllers/ShiftPlanController.php
app/Shared/UserHelper.php
app/ShiftGroup.php
app/ShiftGroupMember.php
app/ShiftPlan.php
app/ShiftPlanHistory.php
app/ShiftPlanStaff.php
app/ShiftPlanStaffDay.php
app/ShiftPlanStaffTemplate.php
config/adminlte.php
database/.gitignore
database/migrations/2019_10_07_083456_create_shift_plans_table.php
database/migrations/2019_10_07_085057_create_shift_plan_histories_table.php
database/migrations/2019_10_07_091124_create_shift_plan_staff_table.php
database/migrations/2019_10_07_091257_create_shift_plan_staff_templates_table.php
database/migrations/2019_10_07_091330_create_shift_plan_staff_days_table.php
database/migrations/2019_10_09_075745_create_shift_groups_table.php
database/migrations/2019_10_09_084634_create_shift_group_members_table.php
resources/lang/vendor/adminlte/en/menu.php
resources/views/shiftplan/shift_group.blade.php
resources/views/shiftplan/shift_group_detail.blade.php
resources/views/shiftplan/splan_list.blade.php
resources/views/staff/punchlist.blade.php
routes/web.php

Shift group creation, assign planner, assign group members

Shift Group Management

---

app/Http/Controllers/URController.php
app/Shared/URHelper.php
app/UserRecord.php
composer.json
database/factories/UserRecordFactory.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2019_10_10_074723_create_user_records_table.php
routes/web.php

To populate the data:
- get the seeder from Amer
- run migration( php artisan db:seed --class=SapPersdata)
- got to ur/popbyid/<persno> or ur/popbyid/all (will have to wait 5 minutes)
- enjoy

data seeder for users, user_records

---

app/Providers/AppServiceProvider.php

fix some login issue in dev
force https

force https

---

app/Http/Controllers/Auth/LoginController.php

https redirect to home after login

https redirect after login

---

app/Http/Controllers/Admin/HolidayController.php
resources/views/admin/holiday/edit.blade.php

update holiday to compare all db data and remove duplicates

update for holiday edit and show

---

app/Http/Controllers/ShiftPlanController.php
app/Http/Controllers/TempController.php
app/Shared/AlertHelper.php
app/ShiftPlanHistory.php
config/adminlte.php
resources/views/shiftplan/plan_detail.blade.php
resources/views/shiftplan/staff_detail.blade.php

shift plans

---

app/Http/Controllers/URController.php
app/Shared/URHelper.php
routes/web.php

- api for user_records
- restore web.php

api for user_records

---

app/Http/Controllers/UserShiftPatternController.php
app/UserShiftPattern.php
composer.lock
database/migrations/2019_12_11_090401_create_salaries_table.php
database/migrations/2020_02_24_135041_create_user_shift_patterns_table.php

user shift patterns
salaries timestamp to datetime

user shift patterns

---

app/Http/Controllers/MiscController.php
resources/views/dashboard/section_main.blade.php
resources/views/home.blade.php
resources/views/vendor/adminlte/page.blade.php

Remove pending chart, 
Remove manpower request (todo),
Re-word wording tile dashboard,

Update Chart, Todo, Tile 

---

app/Shared/UserHelper.php

mix missing class when applying OT

fix get day missing class

---

app/Http/Controllers/Admin/HolidayController.php
app/Http/Controllers/ProfilePicController.php
resources/views/admin/holiday/show.blade.php
resources/views/staff/profile.blade.php

deletion of holiday with " ' "

holiday correction

---

app/Http/Controllers/Admin/PaymentScheduleController.php
app/Http/Controllers/Admin/PsubareaController.php
resources/views/admin/company.blade.php
resources/views/admin/paymentschedule.blade.php
resources/views/admin/psubarea.blade.php
resources/views/vendor/adminlte/page.blade.php

-Pymnt Schdle
-Psubarea
-Compny

Dear Afdzal kindly approve, tq.

---

app/Http/Controllers/Admin/HolidayController.php
app/Http/Controllers/DemoController.php
app/Shared/DataMart.php
app/Shared/GeoLocHelper.php
resources/views/demo/location.blade.php
routes/web.php

resolve error on edit holiday when send blank states
adding demo/location

holiday and geolocation

---

app/Http/Controllers/DemoController.php
app/Shared/GeoLocHelper.php
resources/views/demo/location.blade.php

location api

---

app/Http/Controllers/Admin/OtReport2Controller.php
app/Http/Controllers/Admin/OtSaRepController.php
app/Http/Controllers/ShiftGroupController.php
resources/views/dashboard/section_sysadmin.blade.php
resources/views/report/otMain.blade.php
resources/views/report/sysadmMain.blade.php
resources/views/shiftplan/mygroup.blade.php
resources/views/shiftplan/mygrpdetail.blade.php
routes/web.php

Add route mainpage Report (U,SA), Fix shift planner mod

Report page, Shift Planner

---

app/Http/Controllers/ShiftGroupController.php
resources/views/dashboard/section_sysadmin.blade.php
resources/views/home.blade.php
resources/views/report/otMain.blade.php
resources/views/report/sysadmMain.blade.php
resources/views/shiftplan/mygroup.blade.php
resources/views/shiftplan/mygrpdetail.blade.php

fix program
add back search user 
for shift plan

fix shift plan, remove tile dashboard

---

app/Http/Controllers/Admin/StaffController.php
app/Http/Controllers/TempController.php
app/Http/Controllers/UserVerifierController.php
database/seeds/PermissionsTableSeeder.php
public/vendor/custom.css
resources/lang/vendor/adminlte/en/menu.php
resources/views/admin/staff.blade.php
resources/views/dashboard/section_admin.blade.php
resources/views/dashboard/section_sysadmin.blade.php
resources/views/home.blade.php
resources/views/loginoffline.blade.php
resources/views/staff/profile.blade.php
routes/web.php

Dashboard, Display Profile User

Dashboard, Display Profile User

---

resources/views/shiftplan/mygroup.blade.php
resources/views/shiftplan/mygrpdetail.blade.php

Fix Shift group count
Fix add member from subordinate list

Fix Shift Planner

---

app/DayType.php
app/Http/Controllers/Controller.php
app/Http/Controllers/NotiMenuController.php
app/Http/Controllers/WorkSchedRuleController.php
app/Shared/AlertHelper.php
app/ShiftGroupMember.php
app/ShiftPlanStaffDay.php
resources/views/staff/workcalendar.blade.php
resources/views/staff/workteamcalendar.blade.php

no route named home. changed to misc.home

read nitify link redirect to proper misc.home instead of home

---

app/Api/Datamart/UserShiftPatternController.php

resolve null shift pattern descr from sap

shift pattern

---

app/Http/Controllers/ShiftGroupController.php
app/Http/Controllers/ShiftPlanController.php
app/Notifications/GroupMemberAssigned.php
app/Notifications/GroupOwnerAssigned.php
app/Notifications/GroupPlannerAssigned.php
app/Notifications/ShiftPlanApproved.php
app/Notifications/ShiftPlanMembersApproved.php
app/Notifications/ShiftPlanReverted.php
app/Notifications/ShiftPlanSubmitted.php
public/vendor/custom.css
resources/lang/vendor/adminlte/en/menu.php
resources/views/dashboard/section_sysadmin.blade.php
resources/views/email/shift/groupMemberAssigned.blade.php
resources/views/email/shift/groupOwnerAssigned.blade.php
resources/views/email/shift/groupPlannerAssigned.blade.php
resources/views/email/shift/shiftPlanApproved.blade.php
resources/views/email/shift/shiftPlanMembersApproved.blade.php
resources/views/email/shift/shiftPlanReverted.blade.php
resources/views/email/shift/shiftPlanSubmitted.blade.php
resources/views/shiftplan/mygroup.blade.php
resources/views/shiftplan/mygrpdetail.blade.php
resources/views/shiftplan/plan_detail.blade.php
resources/views/shiftplan/shift_group.blade.php
resources/views/staff/profile.blade.php
resources/views/vendor/adminlte/page.blade.php

Nav Side & Profile
Fix Shift Group & Plan
Update dashboard tiles link
Notify & Todo
Shift Notify & Email

Update Profile, Shift,  Plan, Notify & Email

---

app/Shared/AlertHelper.php
resources/views/vendor/adminlte/page.blade.php

Revert "Add To do"

---

resources/views/staff/workcalendar.blade.php
resources/views/staff/workschedulemain.blade.php
resources/views/staff/workschedulereqs.blade.php
resources/views/staff/workteamcalendar.blade.php

Fix Work Schedule screen request

My Work Schedule screen

---

app/Http/Controllers/MiscController.php
app/Http/Controllers/ShiftGroupController.php
app/Http/Controllers/ShiftPlanController.php
app/Http/Controllers/UserVerifierController.php
public/vendor/custom.css
resources/views/verifier/index.blade copy 2.php
resources/views/verifier/viewGroup.blade.php

put try for email notification.
fix advance search in "Set Default Verifier"
fix display count verification

Shift Email try + Set Default Verifier

---

app/Http/Controllers/UserVerifierController.php

fix verifier search subordinate NE only 7x deep
fix verifier advance search All NE only

fix verifier search NE

---

app/Shared/AlertHelper.php

fix untuk no route error lepas login

todo error

---

app/Shared/AlertHelper.php
resources/views/verifier/index.blade.php
resources/views/verifier/viewGroup.blade.php

Fix todo route claim approval

---

app/Http/Controllers/ShiftGroupController.php
resources/views/shiftplan/shift_group_detail.blade.php

only list non-weekly pattern in shift group creation

---

app/Http/Controllers/MiscController.php
app/Http/Controllers/ShiftGroupController.php
app/Http/Controllers/UserVerifierController.php
app/Http/Controllers/VerifierGroupController.php
resources/views/dashboard/section_admin.blade.php
resources/views/dashboard/section_main.blade.php
resources/views/dashboard/section_shift.blade.php
resources/views/home.blade.php
resources/views/shiftplan/mygroup.blade.php
resources/views/verifier/index.blade.php
resources/views/verifier/viewGroup.blade.php
routes/web.php

set verifier default
1. display all NE 8 tiers below owner
Shift Management
Shift Subordinate Without Group
1. display all NE 8 tiers below owner
2. searching all NE 8 tiers below owner
Dashboard
1. Add tile "Shift Planner/Member Assignment" if has name in approver_id & verifier_id
2. add tile "Shift planning" if has name planner_id
3. add tile "Shift approval" if has name approval_id
4. fix tiles Actual Payment
5. fix tiles Pending Payment
6. fix tiles OT Hour Monthly

changes set verifier default, shift assignment, dashboard

---

app/Http/Controllers/ShiftGroupController.php
resources/views/shiftplan/mygrpdetail.blade.php
resources/views/shiftplan/shift_group.blade.php

Auto generate group code
Change label

Group Code Auto, Label

---

app/Http/Controllers/Admin/ShiftPatternController.php
app/Http/Controllers/WorkSchedRuleController.php
app/ShiftCompPattern.php
database/migrations/2020_06_08_063901_create_shift_comp_patterns_table.php
resources/views/admin/shiftp/stemplate_list.blade.php
resources/views/staff/workcalendar.blade.php
resources/views/staff/workteamcalendar.blade.php

add dropdown month for schedule view
add db structure & view for pattern by comp

add dropdown month for schedule view

---

app/Http/Controllers/Admin/ShiftPatternController.php
app/Http/Controllers/ShiftPlanController.php

run this migration file.
php artisan migrate --path=/database/migrations/2020_06_21_123935_add_start_time_to_shift_patterns.php

shift planning validation 30 hour

---

app/Http/Controllers/ShiftPlanController.php
resources/views/admin/shiftp/daytype.blade.php

check start_time for 30hour not null
remove second in workday display

Fix error start_time & display second

---

app/Http/Controllers/ShiftPlanController.php
resources/views/shiftplan/plan_detail.blade.php
resources/views/shiftplan/staff_detail.blade.php

warning message 30 hour validation
few display changes

30 hour validation

---

app/Http/Controllers/Auth/LoginController.php

login test app::env

---

app/Http/Controllers/Auth/LoginController.php
resources/views/vendor/adminlte/login.blade.php

change call env App::enviroment -> $_ENV['APP_ENV']

Final - hopefully

---

app/UserRecord.php
resources/views/staff/profile.blade.php

fix coscenter subordinate

---

resources/views/staff/profile.blade.php

fix profile reptto

---

resources/views/shiftplan/shift_group_detail.blade.php
resources/views/shiftplan/staff_detail.blade.php

display DayType->description
for HCBD 
for Shift planner

display DayType->description

---

routes/web.php

repair web

---

app/Http/Controllers/Admin/StaffController.php
app/Salary.php
app/User.php
app/UserRecord.php
resources/lang/vendor/adminlte/en/adminlte.php
resources/views/admin/staff.blade.php
resources/views/staff/profile.blade.php
routes/web.php

Revert "user profile update (add searching parameter, user info, return button, excel button)"

---

app/Http/Controllers/ShiftGroupController.php
app/OtIndicator.php
app/User.php
app/ViewShiftGroup.php
config/adminlte.php
resources/lang/vendor/adminlte/en/menu.php
resources/views/admin/shiftGroup.blade.php

User Management -> Shift Group

View shift group all

---

routes/web.php

route admin shiftgroup

---

app/Http/Controllers/WorkSchedRuleController.php
resources/views/admin/shiftGroup.blade.php
resources/views/staff/workcalendar.blade.php
resources/views/staff/workschedulemain.blade.php
resources/views/staff/workschedulereqs.blade.php
resources/views/staff/workteamcalendar.blade.php

-fix workschedule page catter shift view
-add excel download function for view all shiftgroup

workschedule normal/shift & excel shiftgroupall

---

app/Http/Controllers/Admin/OtReport2Controller.php
app/Http/Controllers/Admin/StaffController.php
app/Jobs/ReportOT.php
resources/views/admin/staffidx.blade.php
resources/views/dashboard/section_sysadmin.blade.php
resources/views/report/otrList.blade.php
resources/views/report/otrdetailsList.blade.php
resources/views/staff/profile.blade.php

-Display daytype code(report)
-Replace 'Y'->Actual & 'N'->Limit (Search Staff &User profile)
-Remove return link(user profile) 
-Change user profile link (dashboard)

Report,Search Staff, User profile, Dashboard

---

app/Http/Controllers/ShiftGroupController.php
app/Shared/UserHelper.php

rate issues & info group owner member assignment

rate issues & info group owner member assignment

---

resources/views/staff/otquery.blade.php

adding pagenumber to ot.query.blade to be send to controller

adding pagenumber

---

app/Http/Controllers/OvertimeController.php
app/Http/Middleware/VerifyCsrfToken.php
public/vendor/custom.css
resources/views/staff/otquery.blade.php
resources/views/staff/overtime.blade.php

fix 104
adding pagenumber
fix approval 
enhance submission process 
fix macam2

clean migration from test to prod 20200730

---

app/Http/Controllers/ShiftPlanController.php

fix overflow plan end_date null

fix overflow plan end_date null

---

app/Console/Commands/PHTag.php
app/Http/Controllers/OvertimeController.php

if($wd) line 109

---

app/Http/Controllers/OvertimeController.php
app/Shared/UserHelper.php

remove log due to many dependencies to checkday function

remove log due to many dependencies to checkday function

---

app/Http/Controllers/Admin/OtReport2Controller.php
app/Http/Controllers/Admin/OtSaRepController.php
app/Jobs/ReportOT.php
resources/views/report/otr.blade.php
resources/views/report/otrdetails.blade.php
resources/views/report/sysadmOt.blade.php
resources/views/report/sysadmOtd.blade.php

add new search parameter

---

resources/views/staff/workcalendar.blade.php
resources/views/staff/workschedulemain.blade.php
resources/views/staff/workschedulereqs.blade.php
resources/views/staff/workteamcalendar.blade.php

Workschedule user page display

---

app/Http/Controllers/OvertimeController.php
resources/views/staff/otdetailview.blade.php
resources/views/staff/otquery.blade.php
resources/views/vendor/adminlte/clean.blade.php
routes/web.php

23 - No sorting function in Approver action list - issue raised by SUTE

23 - No sorting function in Approver action list - issue raised by SUTE

---

app/Http/Controllers/OvertimeController.php

Fixes item no 54

---

app/DayType.php
resources/views/admin/shiftp/daytype.blade.php
resources/views/admin/shiftp/stemplate_detail.blade.php

display endtime 0000 to 2400

---

app/Http/Controllers/Admin/OtReport2Controller.php
app/ViewOtRpt2.php

ot_detail report

---

app/Http/Controllers/ShiftGroupController.php
app/Http/Controllers/ShiftPlanController.php
resources/views/admin/shiftGroup.blade.php

Shift group & plan

---

app/Api/USPController.php
resources/views/vendor/adminlte/page.blade.php

persdata datamart issue

---

app/Api/USPController.php
app/Http/Controllers/Admin/DayTypeController.php
database/migrations/2021_02_18_163200_add_exphour_to_daytypes.php
resources/views/admin/shiftp/daytype.blade.php

API SHIFT PATTERN

---

app/Http/Controllers/Admin/ShiftPatternController.php
app/Http/Controllers/ShiftGroupController.php
resources/views/admin/shiftGroupPattern.blade.php
resources/views/admin/shiftp/daytype.blade.php
resources/views/admin/shiftp/stemplate_list.blade.php

SD862062 : Identify and develop solution for NEO issues
Add excel type work day, fix shift group, pattern, planning.

Add excel type work day, fix shift group, pattern, planning

---

app/Http/Controllers/Admin/PayrollgroupController.php

payrollgroup fix

---

app/Http/Controllers/OvertimeController.php
resources/views/staff/otdetail.blade.php
resources/views/staff/otform.blade.php

1.otform claim type project(network header, network act no, change $data->$selectdata)
2.otdetail - Project description

Charge type Project

---

app/DayTag.php
app/Http/Controllers/Admin/DayTagController.php
app/Http/Controllers/Admin/InvalidEmailController.php
app/Http/Controllers/OvertimeController.php
app/InvalidEmail.php
config/adminlte.php
database/migrations/2021_04_27_223502_create_detailsreport_views.php
database/migrations/2021_07_09_145026_create_invalid_emails_table.php
resources/lang/vendor/adminlte/en/menu.php
resources/views/admin/daytagPH.blade.php
resources/views/admin/invalidemail.blade.php
routes/web.php

1)Day tag (new controller and blade)
2)Invalid Email (new migration, controller and blade)
3)detailsreport_views (alter migration file -otd.minute)

PH & email & OTD.minute
